COMMENT=	KDE libraries from git

SUBDIR += libraries6-libkexiv2
SUBDIR += libraries6-libqaccessibilityclient
SUBDIR += libraries6-phonon
SUBDIR += libraries6-plasma-wayland-protocols

.include <bsd.port.subdir.mk>
