COMMENT=	KDE libraries from git

SUBDIR += libraries6-kuserfeedback
SUBDIR += libraries6-libkexiv2
SUBDIR += libraries6-libqaccessibilityclient
SUBDIR += libraries6-phonon
SUBDIR += libraries6-plasma-wayland-protocols
SUBDIR += libraries6-polkit-qt-1
SUBDIR += libraries6-selenium-webdriver-at-spi

.include <bsd.port.subdir.mk>
