PORTNAME=	breeze-icons
DISTVERSION=	${KDE_FRAMEWORKS_VERSION}
CATEGORIES=	x11-themes kde
PKGNAMEPREFIX=	kf5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Breeze icon theme for KDE

RUN_DEPENDS=	kf6-breeze-icons>0:x11-themes/kf6-breeze-icons

USES=		kde:5 metaport

.include <bsd.port.mk>
