COMMENT=	KDE Plasma Desktop from git

SUBDIR += plasma6
SUBDIR += plasma6-breeze
SUBDIR += plasma6-kactivitymanagerd
SUBDIR += plasma6-kdecoration
SUBDIR += plasma6-kglobalacceld
SUBDIR += plasma6-kinfocenter
SUBDIR += plasma6-kpipewire
SUBDIR += plasma6-kscreenlocker
SUBDIR += plasma6-kuserfeedback
SUBDIR += plasma6-kwayland-integration
SUBDIR += plasma6-kwin
SUBDIR += plasma6-layer-shell-qt
SUBDIR += plasma6-libkscreen
SUBDIR += plasma6-libksysguard
SUBDIR += plasma6-milou
SUBDIR += plasma6-oxygen
SUBDIR += plasma6-plasma-desktop
SUBDIR += plasma6-plasma-nano
SUBDIR += plasma6-plasma-wayland-protocols
SUBDIR += plasma6-plasma-workspace
SUBDIR += plasma6-plasma5support
SUBDIR += plasma6-polkit-kde-agent-1
SUBDIR += plasma6-powerdevil
SUBDIR += plasma6-selenium-webdriver-at-spi
SUBDIR += plasma6-systemsettings

.include <bsd.port.subdir.mk>
