PORTNAME=	plasma-workspace-wallpapers
DISTVERSION=	${KDE_PLASMA_VERSION}
PORTREVISION=	1
CATEGORIES=	x11-themes kde
PKGNAMEPREFIX=	plasma5-

MAINTAINER=	kde@FreeBSD.org
COMMENT=	Plasma5 wallpapers
WWW=		https://www.kde.org/plasma-desktop

RUN_DEPENDS=	plasma6-plasma-workspace-wallpapers>0:x11-themes/plasma6-plasma-workspace-wallpapers

USES=		kde:5 metaport

.include <bsd.port.mk>
